### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by peyanski**
I've added Tasmota & Tasmotizer video tutorial link in the readme.

### CODE REVIEW

**Comment by jziolkowski** [comment]
I'd add the link if your video included the usage of "Send config" functions instead of doing it manually. If you are so inclined, please wait for some time because I'm about to release a new version with more options available to pre-configure. Then you can make a new, in-depth video covering all the features.

Until then, I'm putting this PR on hold.

**Comment by peyanski** [comment]
Sorry if I did something wrong. I just want to help. Either way, keep up the good work and I hope that you add OTA as well.

Cheers,
Kiril

**Comment by jziolkowski** [comment]
No, you didn't do anything wrong and I'm grateful for making a video on my application.
We can both benefit from you making a new video: you will have a new content for your channel, and I will have a good tutorial for my app. Win-win :) Just give me some time so I can update Tasmotizer.

**Comment by digiblur** [comment]
Another good one by SuperHouse - https://www.youtube.com/watch?v=hIwIhu5OWiA

**Pull request closed without merging**
