### PR TITLE
Develop 1.3 - Project localization

### PR DESCRIPTION
**Pull request by bovirus**
@Jason2866 

- Create toolss folder with DOS batch file 

to create template
align language files to template
convert po files in mo files

- Add locale structuire for language files

- Modified some .py files to have strings that can be translated.

Please compile it and check if it works fine.

### CODE REVIEW

**Comment by jziolkowski** [comment]
Ok so if I understand that correctly, it requires building a separate file and separate .exe for every language, yes?

**Comment by bovirus** [comment]
@jziolkowski 

One single build contains all languages.

**Comment by jziolkowski** [comment]
Fair enough. The main issue I see is that the translation build chain is windows only. I don't work with windows so I would be practically unable to update/make translations myself... I'd much more prefer these scripts as linux bash scripts (which can be run on windows as well)

**Comment by bovirus** [comment]
@jziolkowski 

I believe that if you can make a test build we can check if it works fine.
You can sure do it of DOS batch in the same way with Linux.
In the same time please leave also the Windows batch files.
I can update if it will be necessary.

**Comment by jziolkowski** [comment]
Ok, before I merge that I will first ask in few places if there's a need for other people to have tasmotizer translated - because someome would have to do the actual translation work. I won't add internalization if it's only for one or two languages.

**Comment by jziolkowski** [comment]
For starters here: https://github.com/tasmota/tasmotizer/discussions/78

**Comment by bovirus** [comment]
@jziolkowski 

Why do you think that one language is not enough?

If tasmota ha several langauges, why tasmnotizer that is a good companion for tasmota project cannot have sevral languages?

I think about to an improvement of tasmotizer that in any momenti can add a new language without change anything more in source code because is ready for multilanguage.

I beleieve that the task did are always good for any new relase/languages in the future.

About two negative anqswer I didn't underatand that.
They told theat tasmota is localized in thier local language but are not intersted about tsnmotizer localized in their language.
Why tasmota localzied and tasmotizer not localzied?

As I told in the new thread we have to think tnot if we like /don't like tio have tasmotizer localzied in our local langauge but if we see negative point to have tasmotizer localzied in our language.

I propose you to change the first post in new thread adding these info (not like/don't like - tell if there are negative points).

I propose you also to add a summary with the votation, with languages in aplhabetical order and OK NOK. Ex.

Argentina - Not interested
Hebrew - not interested
Italian - OK

**Pull request closed without merging**
