### PR TITLE
Upgrade PyQT to version 5.15.6

### PR DESCRIPTION
**Pull request by njh**
I updated PyQT to version 5.15.6 in `requirements.txt` and it all seems to work fine.
This is the latest version of PyQT5 available:
https://pypi.org/project/PyQt5/

Part of the reason for upgrading was I was having trouble installing version 5.14.2.

I instead installed PyQT using Homebrew:
```
% brew install pyqt@5
==> Downloading https://ghcr.io/v2/homebrew/core/qt/5/manifests/5.15.2_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/qt/5/blobs/sha256:36d6beacddb74f9a9a8a58a70903739a20ce8
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:36d6beacddb74f9a9a8
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pyqt/5/manifests/5.15.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pyqt/5/blobs/sha256:05305ba5d0bc3ed5289b64e8df3ed20c1cc
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:05305ba5d0bc3ed5289
######################################################################## 100.0%
==> Installing dependencies for pyqt@5: qt@5
==> Installing pyqt@5 dependency: qt@5
==> Pouring qt@5--5.15.2_1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/qt@5/5.15.2_1: 10,466 files, 191.8MB
==> Installing pyqt@5
==> Pouring pyqt@5--5.15.6.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/pyqt@5/5.15.6: 1,288 files, 33.2MB
==> Running `brew cleanup pyqt@5`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

And then Tasmotizer successfully used the Homebrew installed version.

### CODE REVIEW

**Comment by jziolkowski** [comment]
The reason for pinning PyQt to an older version was serious issues on RaspberryPi. Can you check that?

**Comment by njh** [comment]
Ah! I did wonder why it was pinned.
Yes, I will go and try it out on a Raspberry Pi…

**Comment by njh** [comment]
Hi! I have spent a lot more time on this than I was anticipating!

I used a clean/fresh disk image on a Raspberry Pi 4:
**Image**: 2021-10-30-raspios-bullseye-armhf
**OS**: Debian 11.2 (Bullseye)
**Python**: 3.9.2
**QT**: 5.15.2-2

First I tried building against the current release version of tasmotizer (pyqt5 version 5.14.2).
The build failed:
https://gist.github.com/njh/af95b5c9d7df421178f2953789a6917e

Not quite clear why - put it looks like I might be missing something on my system that is causing the build to fail.

However I then tried building against pyqt5 version 5.15.6, which succeeded 🎉 
I had to make sure that the `libqt5serialport5-dev` Debian package was installed.

Installing pyqt5 on a Raspberry Pi took a very long time because it is built from source every time.
This is because [PyQt5 does not have a successful wheel build in Piwheels](https://www.piwheels.org/project/PyQt5/).

However I was able to run `pip3 wheel pyqt5` successfully, so I commented on this issue:
https://github.com/piwheels/packages/issues/257

**Comment by Jason2866** [comment]
We should change to `PyQt5>=5.14,<6` by doing this all problems should be solved.
All major Linux variants have updated there versions. Mac M1 needs a later 5.x version

**Comment by njh** [comment]
Thanks for reviewing / merging @Jason2866 👍 

I had the following comment in draft that I didn't submit before you merged.

---

I have updated the PR to:
```
PyQt5>=5.14.2,<6
```

On my Mac M1 with Homebrew it now says:
```
% pip3 install -r requirements.txt                                
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pyserial>=3.5 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (3.5)
Requirement already satisfied: PyQt5<6,>=5.14.2 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (5.15.6)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /opt/homebrew/lib/python3.9/site-packages (from PyQt5<6,>=5.14.2->-r requirements.txt (line 2)) (12.9.0)
```

On the Raspberry Pi:
```
pi@raspberrypi:~/Projects/tasmotizer $ pip3 install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyserial>=3.5
  Using cached https://www.piwheels.org/simple/pyserial/pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting PyQt5<6,>=5.14.2
  Using cached PyQt5-5.15.6.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting PyQt5-sip<13,>=12.8
  Using cached https://www.piwheels.org/simple/pyqt5-sip/PyQt5_sip-12.9.0-cp39-cp39-linux_armv7l.whl (267 kB)
Building wheels for collected packages: PyQt5
  Building wheel for PyQt5 (PEP 517) ... done
  Created wheel for PyQt5: filename=PyQt5-5.15.6-cp36-abi3-manylinux1_armv7l.whl size=5251762 sha256=93e707e65e9b67456aad51ef2ab6f566af6b4708e3363e30943c317bdc4b588b
  Stored in directory: /home/pi/.cache/pip/wheels/e2/59/97/3ebe5bf9c908d6001cd6af09b6c27b9960cccf7a2a4b2f6bce
Successfully built PyQt5
Installing collected packages: PyQt5-sip, pyserial, PyQt5
Successfully installed PyQt5-5.15.6 PyQt5-sip-12.9.0 pyserial-3.5
```

**Pull request merged**
